source.. = src/
bin.includes = .,\
               META-INF/,\
               OSGI-INF/,\
               about.html
src.includes = about.html
output.. = bin/


# Maven/Tycho pomless configuration.
tycho.pomless.parent = ../../releng/org.eclipse.cbi.p2repo.analyzers.parent
