source.. = src/
output.. = bin/
bin.includes = META-INF/,\
               .,\
               OSGI-INF/,\
               about.html
src.includes = about.html

# Maven/Tycho pomless configuration.
tycho.pomless.parent = ../../releng/org.eclipse.cbi.p2repo.analyzers.parent
